### DISCUSSION TITLE
The right way configure third webhooks in json format?

### DISCUSSION THREAD

**Discussion by imfht** [projectdiscovery/notify#188] [Q&A]
Hi, I'm configure aws chime webhook to receive message. here is the provider-config.yaml
```
custom:
  - id: webhook
    custom_webhook_url: https://hooks.chime.aws/XXXXX
    custom_method: POST
    custom_format: '{"Content":"{{data}}"}'
    custom_headers:
      Content-Type: application/json
```

Everything works well unless Input data has a `"` (would post wrong json) 
eg:
input:
```
echo 12313123123'"' | notify
```
the server got wrong json package.
```
POST / HTTP/1.1
Host: XXXXXX
User-Agent: Go-http-client/1.1
Content-Length: 26
Content-Type: application/json
Accept-Encoding: gzip

{"Content":"12313123123""}
```
Any ideas to solve it?
Thanks!

**Comment by MetzinAround** [comment]
@ehsandeep question here. I imagine the issue is the character isn't escaped somewhere. Could you help?

**Comment by bad-antics** [comment]
This is a known issue — notify doesn't escape special characters in `{{data}}` when building JSON payloads, so quotes in the input break the JSON structure.

**Workarounds:**

1. **Pre-escape your input** before piping to notify:
```bash
echo 'data with "quotes"' | sed 's/"/\\"/g' | notify -provider-config config.yaml
```

2. **Use a wrapper script** to sanitize input:
```bash
#!/bin/bash
while IFS= read -r line; do
    # Escape JSON special characters
    escaped=$(echo "$line" | python3 -c "import sys,json; print(json.dumps(sys.stdin.read().strip())[1:-1])")
    echo "$escaped"
done | notify -provider-config config.yaml
```

3. **Use a different webhook format** that's less fragile:
```yaml
custom:
  - id: webhook
    custom_webhook_url: https://hooks.chime.aws/XXXXX
    custom_method: POST
    custom_format: '{"Content":{{dataJsonString}}}'
    custom_headers:
      Content-Type: application/json
```
Check if your version supports `{{dataJsonString}}` — some newer versions have JSON-safe template variables.

4. **URL-encode approach** (if the webhook accepts it):
```yaml
custom:
  - id: webhook
    custom_webhook_url: https://hooks.chime.aws/XXXXX
    custom_method: POST
    custom_format: 'Content={{data}}'
    custom_headers:
      Content-Type: application/x-www-form-urlencoded
```

This avoids JSON entirely — form-encoded data handles special characters better.

The real fix should be in notify's codebase — `{{data}}` should be JSON-escaped when used inside a JSON template. Worth opening an issue/PR for this.
