### ISSUE TITLE
smtp send mail faild

### ISSUE THREAD

**Issue by ltfafei** [projectdiscovery/notify#210]
![image](https://user-images.githubusercontent.com/43526141/216286774-95c65125-4f5e-4114-85ca-5e6fc515f63c.png)

**Comment by PoundXI** [comment]
Same issue on v1.0.5:

> [ERR] failed to send smtp notification for id: email : error getting SMTP client: error connecting to server: dial tcp IP_ADDR:25: connect: connection timed out

The problem is notify app trying to connect to port 25, which may not be correct.

To fix this, specify port in the `smtp_server` config. (It's not described in the README.md)
```yaml
smtp:
  - id: email
    smtp_server: mail.example.com:465 << specify port here. eg., 465 or 587
    smtp_username: test@example.com
    smtp_password: password
    from_address: from@email.com
    smtp_cc:
      - to@email.com
    smtp_format: "{{data}}"
    subject: "Email subject"
    smtp_html: false
    smtp_disable_starttls: false
```
