### ISSUE TITLE
SMTP provider does not allow to configure UseStartTLS 

### ISSUE THREAD

**Issue by S0obi** [projectdiscovery/notify#222]
### Please describe your feature request:
Even if the [shoutrrr](https://containrrr.dev/shoutrrr/v0.5/services/email/) library does support this configuration, it's not possible to easily configure it with notify.

Currently, we are using an ugly hack by injecting this parameter into the `subject` variable: 

```yaml
  - id: email
    smtp_server: smtpinternal.test.test
    smtp_username: ""
    smtp_password: ""
    from_address: no-reply@test.com
    smtp_cc:
      - test@test.com
    smtp_format: "{{data}}"
    subject: "Test&UseStartTLS=false"
```

### Describe the use case of this feature:
This feature will allow to configure easily the UseStartTLS parameter.
