### ISSUE TITLE
Reading keys from environment variables

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/notify#245]
Similar to
- https://github.com/projectdiscovery/cloudlist/issues/249
- https://github.com/projectdiscovery/nuclei/issues/3015

### Please describe your feature request:

Allow reading reporting config values from as env variable to avoid storing sensitive keys/credentials as plain text in a reporting and flag config file.

```
$ cat config.yaml
```

```yaml
slack:
  - id: recon
    slack_channel: $SLACK_CHANNEL
    slack_username: $SLACK_USER
    slack_webhook_url: $SLACK_WEBHOOK
```
### Describe the use case of this feature:

```
cat output | notify -pc config.yaml
```
