### ISSUE TITLE
Discord messages appear as embeds rather than plaintext

### ISSUE THREAD

**Issue by mikedesu** [projectdiscovery/notify#303]
See screenshots.

![Screenshot_2023-09-01_00-47-16](https://github.com/projectdiscovery/notify/assets/165251/11876a90-3063-488e-bcd5-b73afa69496c)

I managed to get the plaintext working by doing a raw curl to the webhook address with a simple JSON format message. I tried digging through the go source code but it is not my language. Wherever the JSON is constructed before doing the post, the tweak should be done there.

It'd be nice to have an option of either embeds -or- plaintext, but the reason I need plaintext is that I'm trying to chain `notify-discord` to `matterbridge-irc`. I can do it with the raw curl now, but it would be nice if I could use `notify` for this...`matterbridge` won't read the embed, but it WILL read the plaintext. 

![Screenshot_2023-09-01_00-47-30](https://github.com/projectdiscovery/notify/assets/165251/f05a8965-1e9b-41f5-b48f-28d9b1c11f78)

**Comment by 0xJeti** [comment]
@mikedesu You can get plaintext Discord message by using `custom` webhook:
```yaml
custom:
  - id: webhook
    custom_webhook_url: "https://discord.com/api/webhooks/..."
    custom_method: POST
    custom_format: '{"content":"{{data}}"}'
    custom_headers:
      Content-Type: application/json
```
