### ISSUE TITLE
Adding support for posting data to custom webhook URL

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/notify#36]
Suggested by Roni (on discord)

Example config:-

```yaml
custom:
  - id: webhook
    custom_webook_url: http://0.0.0.0/api/webhook
    custom_method: GET
    custom_format: '{{data}}'
    custom_headers:
      Content-Type: application/json
      X-Api-Key: XXXXX
```
