### ISSUE TITLE
[FTL] Could not run notifier: notify works with stdin or file using -data flag

### ISSUE THREAD

**Issue by GangGreenTemperTatum** [projectdiscovery/notify#377]
Thanks for the awesome tool contribution! 👋🏼 

### Notify version:
```shell
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian

notify --version
[INF] Current Version: 1.0.6

go version go1.22.3 linux/amd64
```

### Current Behavior:
Unable to run a test of a Slack provider configuration to verify webhook working successfully

### Expected Behavior:
This use to work beforehand, expecting test Slack notification for objective of a bigger workflow which is dependent on `notify`

### Steps To Reproduce:
1. Test `notify` with a simple Slack config
a. `~/go/bin# notify --config-path ./slack-notify.yaml`

### Anything else:
Sample Slack config:
```shell
~/go/bin# cat ./slack-notify.yaml
slack:
  - id: "x Slack"
    slack_channel: "x"
    slack_username: "y"
    slack_format: "{{data}}"
    slack_webhook_url: "https://hooks.slack.com/services/X/Y/Z"
```
Issue seems related to `go` itself, rather than `notify`(?)

**Comment by dogancanbakir** [comment]
Couldn't repro the issue
<img width="611" alt="image" src="https://github.com/projectdiscovery/notify/assets/65292895/8d74738e-b979-43f2-9fc1-80ba30498e7a">

```yaml
slack:
  - id: "slack"
    slack_channel: "x"
    slack_username: "y"
    slack_format: "{{data}}"
    slack_webhook_url: "https://hooks.slack.com/services/x/y/z"
```
