### ISSUE TITLE
Discord integration sends empty messages

### ISSUE THREAD

**Issue by ahmedgomaaa** [projectdiscovery/notify#378]
Notify version:
1.0.6

Current Behavior:
when trying to set notify to send messages over discord, it sends empty messages with not content.
this is not problem with the discord webhook as it works just fine if POST request is sent, the messages are sent as normal, but for some reason, notify sends empty message

Expected Behavior:
should send correct messages

Steps To Reproduce:

steps to reproduce the behavior:
1. Set provider-config.yaml to the the webhook

```
discord:
  - id: "subs"
    discord_channel: "bbh"
    discord_username: "Spidey Bott"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/*************(REDACTED_WEBHOOK_URL)"
```

2. run notify, for example, echo 'hi' | notify -pc ./provider-config.yaml 
3. See that messages are being sent empty

Screenshots:

![image](https://github.com/projectdiscovery/notify/assets/37199252/9b2d6a95-b3ed-4b07-bd5b-8f4e4971c4d1)

**Comment by dogancanbakir** [comment]
Couldn't repro the issue with the same config:

<img width="761" alt="image" src="https://github.com/projectdiscovery/notify/assets/65292895/9d28732d-2e77-4345-b522-cda470b70374">


```yaml
discord:
  - id: "subs"
    discord_channel: "#general"
    discord_username: "dogancanbakir-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/XXX/YYY"
```
