### ISSUE TITLE
The JSON data still cut even we set  (-cl) flag for char-limit in custom webhook

### ISSUE THREAD

**Issue by ph-hitachi** [projectdiscovery/notify#412]
### Notify version:
 1.0.6

### Current Behavior:
even we set the char-limit the json output still cut on custom webhook

### Expected Behavior:
the full json output will be sent to webhook

### Steps To Reproduce:
` nuclei -t dast/vulnerabilities -dast -j -silent | notify -id webhook -cl 500000`

### Anything else:
![image](https://github.com/user-attachments/assets/b669b083-86c2-48b0-ae10-f05a8017d047)

### Config:
```
custom:
  - id: webhook
    custom_webhook_url: http://7iqcjx7fpxndjc1lztepvuvj6ac10rog.oastify.com/api/subdomins/webhook
    custom_method: GET
    custom_format: '{"text":{{data}} }'
    custom_headers:
      Content-Type: application/json
      X-Api-Key: XXXXX
  ```
