### ISSUE TITLE
Multi-time support for exsiting webhooks

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/notify#43]
Currently, notify doesn't support reusing the same webhook multiple time with different keys/tokens.

For example, if we have the following entry in the config file:-

```yaml
discord_webhook_url: https://discord.com/api/webhooks/7730624177430/XXXX
discord_username: A
discord: true

discord_webhook_url: https://discord.com/api/webhooks/77306241774308/YYYY
discord_username: B
discord: true
```

Notify will only post to 2nd `discord_webhook_url` and the same goes for any other webhook, slack, telegram.

### With this support -
For the cases when we want to post the same results on multiple servers/channels, we can simply define the webhook multiple times in config with different values to achieve this.
