### ISSUE TITLE
Data format customization with CLI and Config file

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/notify#64]
Description:-

Notify supports, multiple providers to push data and all have different UX/UI based on the format of the msg, so it's always a good idea to have control over the format around data to make it easily viewable in markdown or any format that a specific provider supports.

As default, notify doesn't add or should not add any formatting to the data and push it as it is, additionally we can have support for custom formatting via flag and config file.

CLI flag: `msg-format`

CLI example:-

```
notify -msg-format '`{{data}}`'
```

Config support:-

```yaml
$provider_format: '{{data}}'
```

Config example:-

```yaml
discord:
  - profile: test1
    discord_webhook_url: https://discord.com/api/webhooks/XX/XX
    discord_username: test
    discord_channel: notify-test
    discord_format: '{{data}}' # default format
    
discord:
  - profile: test2
    slack_webhook_url: https://xxxx/xxx
    slack_username: test
    slack_channel: notify-test
    slack_format: '`{{data}}`' # custom format
    
telegram:
  - profile: test
    telegram_apikey: xxxx
    telegram_chat_id: xxxx
    telegram_format: | # custom format
    		```
    		{{data}}
    		```
```

This support is optional, as data formatting is disabled as default, if enabled using CLI,  CLI flag format will be applied to all providers regardless of the format defined in the config, otherwise, each provider can be formatted differently if specified and used with the config file.
