### ISSUE TITLE
Updating profiles with ids

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/notify#65]
We added `profile` field support in the config file and profile flag to use any specific profile instead of all providers at once.

Example:-

```
notify -profile recon_subfinder
```

```yaml
discord:
  - profile: recon_subfinder
    discord_webhook_url: https://discord.com/api/webhooks/XX/XX
    discord_username: test
    discord_channel: notify-test
```

We can update the profile with `id` to improve the UX and simple to use.

After change:-

```
notify -id recon,hack
```

```yaml
discord:
  - id: recon
    discord_webhook_url: https://discord.com/api/webhooks/XX/XX
    discord_username: test
    discord_channel: notify-test
    
  - id: hack
    discord_webhook_url: https://discord.com/api/webhooks/XX/XX
    discord_username: hack
    discord_channel: hack-test
```
