### ISSUE TITLE
Bug in sending notification to multiple instances of same provider

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/notify#70]
Using the following config with two unique `discord_webhook_url`

```yaml
discord:
  - id: test1
    discord_webhook_url: https://discord.com/api/webhooks/XXX
    discord_username: test
    discord_channel: notify-test
    discord_format: '{{data}}'
  - id: test2
    discord_webhook_url: https://discord.com/api/webhooks/YYY
    discord_username: test2
    discord_channel: notify-test2
    discord_format: '{{data}}'
```

Used cmd:-

```
notify -bulk -data test.txt
notify -bulk -data test.txt -id test1,test2
```

In both cases, it is expected that notification will be sent to both webhooks which is not happening, same with other providers as well.

This is related to https://github.com/projectdiscovery/notify/issues/43
