### ISSUE TITLE
Blank text in discord

### ISSUE THREAD

**Issue by gauravnarwani97** [projectdiscovery/notify#78]
HI Im using discord webhook integration but observing blank texts while using notify.

config:

```yaml
discord:
  - id: "asd"
    discord_channel: "#general"
    discord_username: "Alerts"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/XXXXXX"
```

<img width="1034" alt="Screenshot 2021-08-27 at 2 21 32 AM" src="https://user-images.githubusercontent.com/26684298/131034336-e8e71ba4-c542-4f20-bae0-236cbaff3699.png">

Getting blank texts
